-- Script para crear las tablas en Supabase para Zytro Vision

-- 1. Tabla de Usuarios
CREATE TABLE IF NOT EXISTS usuarios (
    username TEXT PRIMARY KEY,
    password TEXT NOT NULL,
    role TEXT,
    nombre TEXT,
    cargo TEXT,
    registro TEXT,
    telefono TEXT,
    firma_base64 TEXT,
    accesos JSONB
);

-- 2. Tabla de Pacientes
CREATE TABLE IF NOT EXISTS pacientes (
    id TEXT PRIMARY KEY,
    identificacion TEXT,
    nombre TEXT,
    nombres TEXT,
    apellidos TEXT,
    genero TEXT,
    direccion TEXT,
    edad TEXT,
    fecha_nacimiento TEXT,
    telefono TEXT,
    correo TEXT,
    ocupacion TEXT,
    sucursal TEXT
);

-- 3. Tabla de Historias Clínicas
CREATE TABLE IF NOT EXISTS historias_clinicas (
    id TEXT PRIMARY KEY,
    paciente_id TEXT,
    paciente_nombre TEXT,
    fecha TEXT,
    ant_personales TEXT,
    ant_familiares TEXT,
    motivo TEXT,
    diabetes TEXT,
    hipertension TEXT,
    patologia_otra TEXT,
    observaciones TEXT,
    lenso_od TEXT,
    lenso_av_lej_od TEXT,
    lenso_av_cer_od TEXT,
    lenso_oi TEXT,
    lenso_av_lej_oi TEXT,
    lenso_av_cer_oi TEXT,
    rx_od TEXT,
    rx_av_lej_od TEXT,
    rx_av_cer_od TEXT,
    rx_oi TEXT,
    rx_av_lej_oi TEXT,
    rx_av_cer_oi TEXT,
    estado_muscular TEXT,
    seg_externo TEXT,
    test_colores TEXT,
    estado_refractivo TEXT,
    diagnostico TEXT,
    disposicion TEXT,
    recomendaciones TEXT,
    meses_proximo_control TEXT,
    necesita_lentes TEXT,
    test_color TEXT,
    sucursal TEXT
);

-- 4. Tabla de Auditoría
CREATE TABLE IF NOT EXISTS auditoria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha_hora TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    usuario TEXT,
    nombre_usuario TEXT,
    accion TEXT,
    entidad TEXT,
    detalle TEXT,
    sucursal TEXT
);

-- 5. Tabla de Inventario (Monturas y Productos)
CREATE TABLE IF NOT EXISTS inventario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_barras TEXT,
    marca TEXT,
    modelo TEXT,
    tipo TEXT,
    color TEXT,
    precio_compra NUMERIC,
    precio_venta NUMERIC,
    cantidad_disponible NUMERIC,
    sucursal TEXT
);

-- 6. Tabla de Órdenes de Trabajo
CREATE TABLE IF NOT EXISTS ordenes_trabajo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    creado_el TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    paciente_id TEXT,
    paciente_nombre TEXT,
    estado TEXT,
    abono NUMERIC,
    saldo NUMERIC,
    total NUMERIC,
    metodo_pago TEXT,
    fecha_entrega TEXT,
    rx_od TEXT,
    rx_oi TEXT,
    tipo_lente TEXT,
    laboratorio TEXT,
    sucursal TEXT
);

-- 7. Tabla de Caja Diaria
CREATE TABLE IF NOT EXISTS caja_diaria (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT,
    sucursal TEXT,
    abierta_por TEXT,
    cerrada_por TEXT,
    monto_apertura NUMERIC,
    monto_cierre NUMERIC,
    estado TEXT
);

-- 8. Tabla de Gastos
CREATE TABLE IF NOT EXISTS gastos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT,
    sucursal TEXT,
    categoria TEXT,
    monto NUMERIC,
    usuario TEXT,
    descripcion TEXT
);

-- 9. Tabla de Ventas
CREATE TABLE IF NOT EXISTS ventas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    sucursal TEXT,
    total NUMERIC,
    costo_total NUMERIC,
    abono NUMERIC,
    metodo_pago TEXT,
    cliente TEXT,
    detalles JSONB
);

-- 10. Tabla de Sucursales
CREATE TABLE IF NOT EXISTS sucursales (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre TEXT,
    direccion TEXT,
    telefono TEXT,
    ciudad TEXT
);

-- 11. Tabla de Citas
CREATE TABLE IF NOT EXISTS citas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha TEXT,
    hora TEXT,
    paciente_nombre TEXT,
    motivo TEXT,
    sucursal TEXT
);

-- Configuración de seguridad: Habilitar el acceso a todas las tablas (MVP Abierto)
DO $$
DECLARE
    row record;
BEGIN
    FOR row IN SELECT tablename FROM pg_tables WHERE schemaname = 'public' LOOP
        EXECUTE 'ALTER TABLE public.' || quote_ident(row.tablename) || ' ENABLE ROW LEVEL SECURITY;';
        EXECUTE 'DROP POLICY IF EXISTS "Allow all" ON public.' || quote_ident(row.tablename) || ';';
        EXECUTE 'CREATE POLICY "Allow all" ON public.' || quote_ident(row.tablename) || ' FOR ALL TO anon USING (true) WITH CHECK (true);';
    END LOOP;
END;
$$;
